# Site settings
title: Kağan Akpınar
description: 
url:
author:
  name: "Kağan Akpınar"
  email: "kaganakpinar30@gmail.com"
  twitter: kgn_akpnr

# Build settings
baseurl: # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

Plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
